### PR TITLE
Build against hdf5 1.10.4 as well

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@conda-forge-admin, please re-render.

**Comment by tschoonj** [comment]
@conda-forge-admin, please re-render.

**Comment by tschoonj** [comment]
@beckermr I am trying to force a build against HDF5 1.10.4, but this seems to be ignored. I thought `conda_build_config.yaml` was the right way for this?

**Comment by beckermr** [comment]
You should add both versions to the local config, both 1.10.4 and 1.10.5. Also, I think you need to rerender the feedstock locally. Usually, a pinnings change requires a successful rerender, I think.

**Comment by tschoonj** [comment]
This doesnt work unfortunately... the rerender still insists that there are no changes locally.

**Comment by beckermr** [comment]
Wow ok. I’m very confused as to why this doesn’t work. Maybe let’s try @conda-forge/staged-recipes to see if they have suggestions.

**Comment by sodre** [comment]
It looks like hdf5 is not listed in the build and/or runtime dependencies.

**Comment by beckermr** [comment]
Lol whoops

**Comment by beckermr** [comment]
Thanks and yeah this will do it

**Comment by beckermr** [comment]
@tschoonj hdf5 is pinned globally in conda-forge. Does this feedstock actually depend on it, or is it maybe another package in your env?

**Comment by tschoonj** [comment]
I didn't put in `hdf5` as a dependency because `vtk` drags it in already.

Adding it explicitly does seem to have an impact on `conda smithy rerender`

**Pull request merged**
