### PR TITLE
Manual migration to 3.4.1 & vtk 903

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hey @Anthchirp, it would be great if you could merge this in. 

The PR both bumps the version and pulls in the latest vtk migration. It drops support of Python 3.6, as it was dropped upstream. There is one new patch, as for some reason numpy 1.18 can't find the fftw3 include directories on Windows; I added a comment that this can be dropped later on. It's not a big deal, as it's the standard include path that also comes with numpy ..

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
Thank you!

**Pull request merged**
