### PR TITLE
v3.2.0 update

### PR DESCRIPTION
**Pull request by Anthchirp**
Update and remove @tschoonj as maintainer.
Closes #6

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
Vielen dank!

**Comment by Anthchirp** [comment]
Bitteschön. Nice hearing from you. Hope all is going well and you're steering clear from software packages containing the `cc` letters.

**Comment by tschoonj** [comment]
> Bitteschön. Nice hearing from you. Hope all is going well and you're steering clear from software packages containing the `cc` letters.

Yeah all is well at the Franklin. Not much luck avoiding the CC packages though... CCP4 and CCPEM are still very much keeping me busy!

I heard you also got a new job within Diamond, congrats for that! Hope you don't miss scisoft too much 😄

**Pull request merged**
