### PR TITLE
Try v3.1.0 update

### PR DESCRIPTION
**Pull request by Anthchirp**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
Hey @Anthchirp ! How is it going?

Feel free to become owner of this repo... I am not maintaining this feedstock anymore.

**Comment by Anthchirp** [comment]
Hey Tom, I went with the less confrontative just-add-myself-approach, but if you like I can take you off 🙂 

Will only do this if I can get it to build though 😄

**Comment by Anthchirp** [comment]
btw while you're here - I think you can close your PR at https://github.com/bonsudev/bonsu/pull/1. This was "merged" by the author by virtue of including that change in one massive commit. I have absolutely no idea why that PR is not showing as conflicting.

**Comment by tschoonj** [comment]
Please do take me off then 😄 

IIRC this package is a pain to build. Not sure the conda build ever worked properly.

**Comment by tschoonj** [comment]
Yeah the dev is following a rather unusual git workflow... Thanks will close it.

**Comment by Anthchirp** [comment]
I see green ticks. If you could merge this then I'll take you off with a following update.

**Pull request merged**
